// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bgQC5E6PVH-u_x6vMT5YDwl0HpLVko8',
    appId: '1:659260323376:web:2c4d52bb5f5175db205ff5',
    messagingSenderId: '659260323376',
    projectId: 'form-submit-app-59052',
    authDomain: 'form-submit-app-59052.firebaseapp.com',
    storageBucket: 'form-submit-app-59052.firebasestorage.app',
    measurementId: 'G-WX61PWZMN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDMAicWuPT9jlZzGbTHvpgU-SvOlmJu0',
    appId: '1:659260323376:android:f6ee67121b8251d4205ff5',
    messagingSenderId: '659260323376',
    projectId: 'form-submit-app-59052',
    storageBucket: 'form-submit-app-59052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkDElS90lJxpsSoWE9EGrVq7ea8_IktIs',
    appId: '1:659260323376:ios:0d0144892f64c0e2205ff5',
    messagingSenderId: '659260323376',
    projectId: 'form-submit-app-59052',
    storageBucket: 'form-submit-app-59052.firebasestorage.app',
    iosBundleId: 'com.example.formSubmitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkDElS90lJxpsSoWE9EGrVq7ea8_IktIs',
    appId: '1:659260323376:ios:0d0144892f64c0e2205ff5',
    messagingSenderId: '659260323376',
    projectId: 'form-submit-app-59052',
    storageBucket: 'form-submit-app-59052.firebasestorage.app',
    iosBundleId: 'com.example.formSubmitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7bgQC5E6PVH-u_x6vMT5YDwl0HpLVko8',
    appId: '1:659260323376:web:fe612eafd928ccd0205ff5',
    messagingSenderId: '659260323376',
    projectId: 'form-submit-app-59052',
    authDomain: 'form-submit-app-59052.firebaseapp.com',
    storageBucket: 'form-submit-app-59052.firebasestorage.app',
    measurementId: 'G-MBNQW5FXZY',
  );
}
